/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 pikachu.glb -t -s 
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pikachu-version-2-3994970313504a10be6cb09082d55e86
Title: Pikachu version 2
*/

import * as THREE from "three";
import React from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.SkinnedMesh;
    Object_7: THREE.SkinnedMesh;
    Object_8: THREE.SkinnedMesh;
    Object_9: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    Material_160: THREE.MeshStandardMaterial;
    Material_161: THREE.MeshStandardMaterial;
    Material_162: THREE.MeshStandardMaterial;
    Material_163: THREE.MeshStandardMaterial;
  };
};

export function Pikachu(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/pikachu.glb",
  ) as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={[0.1, 0.1, 0.1]}
      position-y={-2}
    >
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Material_160}
      >
        <SharedOutline />
      </mesh>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Material_161}
      >
        <SharedOutline />
      </mesh>
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Material_162}
      >
        <SharedOutline />
      </mesh>
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Material_163}
      >
        <SharedOutline />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/pikachu.glb");

function SharedOutline() {
  // @ts-ignore
  return <Outlines thickness={0.1} color="black" />;
}
